version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:Shi@9910@db:5432/postgres
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shi@9910

  redis:
    image: redis:7

