# Generated by Django 5.2.2 on 2025-06-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_current_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='Customer',
            new_name='customer',
        ),
    ]
